name: GH Event Types
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# Bump bump
jobs:
  envVars:
    runs-on: [ubuntu-latest]
    steps:
      - run: printenv
    
  displayEventTypes:
    runs-on: [ubuntu-latest]
    steps:
      - run: echo event_name ${{github.event_name}}
      - run: echo sha ${{github.sha}}
      
  outputsTest:
    runs-on: [ubuntu-latest]
    steps:
      - id: foo
        run: echo "exists=false" >> $GITHUB_OUTPUT
        
      - if: ${{ steps.foo.outputs.exists == 'false' }}
        run: echo "was false string"
      - if: ${{ steps.foo.outputs.exists == false }}
        run: echo "was false bool"
      - if: ${{ steps.foo.outputs.exists == 'true' }}
        run: echo "was true string"
      - if: ${{ steps.foo.outputs.exists == true }}
        run: echo "was true bool"
      
