name: GH Event Types
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  displayEventTypes:
    runs-on: [ubuntu-latest]
    steps:
      - run: echo event_name ${{github.event_name}}
